### PR TITLE
feat: Create a few code snippets as examples for using Spanner Graph in Python

### LINKED ISSUE #1185: Create samples for Cloud Spanner Graph
There are currently several examples for how to use Cloud Spanner with Python.
With the recent announcement of the introduction of Spanner Graph, some examples of how to use graph features in Spanner are useful to have.
The goal here is to create some simple samples.

### PR DESCRIPTION
**Pull request by bharadwajvr**
Add a few code snippets to illustrate how to use Spanner Graph functionality in Python. These examples resemble other snippets for how various other Spanner features can be used.

- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-spanner/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1185 🦕

### CODE REVIEW

**Comment by bharadwajvr** [comment]
I did not find instructions for this in the authoring guide - how do I obtain code coverage information for the new code I've written? There is an ask in the description to verify that " Code coverage does not decrease (if any source code was changed)"

**Comment by bharadwajvr** [comment]
A reminder

**Comment by harshachinta** [comment]
@bharadwajvr Thanks for the PR. Will review it early next week.

**Comment by harshachinta** [comment]
> I did not find instructions for this in the authoring guide - how do I obtain code coverage information for the new code I've written? There is an ask in the description to verify that " Code coverage does not decrease (if any source code was changed)"

Looking at the files changed, there is no source file changes in this PR. So this can be ignored.

**Comment by bharadwajvr** [comment]
> @bharadwajvr Thanks for the PR. Will review it early next week.

Thank you @harshachinta

**Comment by harshachinta** [comment]
Adding Do not merge to check the presubmit build status before merging

**Comment by harshachinta** [comment]
@bharadwajvr 
Can you please fix the failing lint
image

**Comment by bharadwajvr** [comment]
> @bharadwajvr Can you please fix the failing lint image

Done. Local run succeeds

```
$ flake8 --show-source --builtin=gettext --max-complexity=20 '--exclude=.nox,.cache,env,lib,generated_pb2,*_pb2.py,*_pb2_grpc.py' --ignore=E121,E123,E126,E203,E226,E24,E266,E501,E704,W503,W504,I202 --max-line-length=88
$
```

**Pull request merged**
