### PR TITLE
tests: check / retry 'instance.exists' before creating database

### LINKED ISSUE #390: samples.samples.quickstart_test: test_quickstart failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 3132587453f7bd0be72ebc393626b5c8b1bab982
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/7d78f9ad-4b52-4472-9847-94be332f8559), [Sponge](http://sponge2/7d78f9ad-4b52-4472-9847-94be332f8559)
status: failed
<details><summary>Test output</summary><br><pre>args = (parent: "projects/python-docs-samples-tests/instances/test-instance"
create_statement: "CREATE DATABASE `my-database-id`"
,)
kwargs = {'metadata': [('google-cloud-resource-prefix', 'projects/python-docs-samples-tests/instances/test-instance/databases/m...-samples-tests/instances/test-instance'), ('x-goog-api-client', 'gl-python/3.6.13 grpc/1.38.1 gax/1.30.0 gccl/3.6.0')]}

    @six.wraps(callable_)
    def error_remapped_callable(*args, **kwargs):
        try:
>           return callable_(*args, **kwargs)

.nox/py-3-6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <grpc._channel._UnaryUnaryMultiCallable object at 0x7f43237f3cc0>
request = parent: "projects/python-docs-samples-tests/instances/test-instance"
create_statement: "CREATE DATABASE `my-database-id`"

timeout = None
metadata = [('google-cloud-resource-prefix', 'projects/python-docs-samples-tests/instances/test-instance/databases/my-database-id...s-samples-tests/instances/test-instance'), ('x-goog-api-client', 'gl-python/3.6.13 grpc/1.38.1 gax/1.30.0 gccl/3.6.0')]
credentials = None, wait_for_ready = None, compression = None

    def __call__(self,
                 request,
                 timeout=None,
                 metadata=None,
                 credentials=None,
                 wait_for_ready=None,
                 compression=None):
        state, call, = self._blocking(request, timeout, metadata, credentials,
                                      wait_for_ready, compression)
>       return _end_unary_response_blocking(state, call, False, None)

.nox/py-3-6/lib/python3.6/site-packages/grpc/_channel.py:946: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <grpc._channel._RPCState object at 0x7f43237f52e8>
call = <grpc._cython.cygrpc.SegregatedCall object at 0x7f43237a2f88>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E           	status = StatusCode.NOT_FOUND
E           	details = "Instance not found: projects/python-docs-samples-tests/instances/test-instance"
E           	debug_error_string = "{"created":"@1624700026.817055527","description":"Error received from peer ipv4:74.125.135.95:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Instance not found: projects/python-docs-samples-tests/instances/test-instance","grpc_status":5}"
E           >

.nox/py-3-6/lib/python3.6/site-packages/grpc/_channel.py:849: _InactiveRpcError

The above exception was the direct cause of the following exception:

    @pytest.fixture
    def example_database():
        spanner_client = spanner.Client()
        instance = spanner_client.instance(SPANNER_INSTANCE)
        database = instance.database("my-database-id")
    
        if not database.exists():
>           database.create()

quickstart_test.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../google/cloud/spanner_v1/database.py:374: in create
    future = api.create_database(request=request, metadata=metadata)
../../google/cloud/spanner_admin_database_v1/services/database_admin/client.py:615: in create_database
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
.nox/py-3-6/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
.nox/py-3-6/lib/python3.6/site-packages/google/api_core/grpc_helpers.py:69: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = None
from_value = <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Instance not found: project...066,"grpc_message":"Instance not found: projects/python-docs-samples-tests/instances/test-instance","grpc_status":5}"
>

>   ???
E   google.api_core.exceptions.NotFound: 404 Instance not found: projects/python-docs-samples-tests/instances/test-instance

<string>:3: NotFound</pre></details>

### PR DESCRIPTION
**Pull request by tseaver**
Closes #390.

### CODE REVIEW

**Review by larkee — COMMENTED** [review]
I don't think the default settings of `RetryResult` is suitable for this case.

The default settings are as follows:
```
MAX_TRIES = 4
DELAY = 1s
BACKOFF = 2 
```

I think setting the delay to 15 may make more sense. WDYT?

**Comment by tseaver** [comment]
@larkee The failure in the sample test (see #390) occurs here:  I've certainly seen other cases where an LRO succeeds, but subsequent `GET` requests fail due to eventual consistency.

> I think the actual fix would be to update the pytest.fixture decorator to something similar to the `test_snippets` setup.

The use of fixtures in that module is actually a little wonky:  very few of the testcases declare their dependencies, and in fact they can't be run separately, because they rely on *other* testcases having run first, as I found out when trying to debug one of the failing samples last week.

```bash
$ git grep "def test" samples/samples/snippets_test.py
samples/samples/snippets_test.py:def test_create_instance(spanner_instance):
samples/samples/snippets_test.py:def test_create_instance_with_processing_units(capsys):
samples/samples/snippets_test.py:def test_create_database(database):
samples/samples/snippets_test.py:def test_create_database_with_encryption_config(capsys, spanner_instance):
samples/samples/snippets_test.py:def test_insert_data(capsys):
samples/samples/snippets_test.py:def test_delete_data(capsys):
samples/samples/snippets_test.py:def test_query_data(capsys):
samples/samples/snippets_test.py:def test_add_column(capsys):
samples/samples/snippets_test.py:def test_read_data(capsys):
samples/samples/snippets_test.py:def test_update_data(capsys):
samples/samples/snippets_test.py:def test_read_stale_data(capsys):
samples/samples/snippets_test.py:def test_read_write_transaction(capsys):
samples/samples/snippets_test.py:def test_query_data_with_new_column(capsys):
samples/samples/snippets_test.py:def test_add_index(capsys):
samples/samples/snippets_test.py:def test_query_data_with_index(capsys):
samples/samples/snippets_test.py:def test_read_data_with_index(capsys):
samples/samples/snippets_test.py:def test_add_storing_index(capsys):
samples/samples/snippets_test.py:def test_read_data_with_storing_index(capsys):
samples/samples/snippets_test.py:def test_read_only_transaction(capsys):
samples/samples/snippets_test.py:def test_add_timestamp_column(capsys):
samples/samples/snippets_test.py:def test_update_data_with_timestamp(capsys):
samples/samples/snippets_test.py:def test_query_data_with_timestamp(capsys):
samples/samples/snippets_test.py:def test_create_table_with_timestamp(capsys):
samples/samples/snippets_test.py:def test_insert_data_with_timestamp(capsys):
samples/samples/snippets_test.py:def test_write_struct_data(capsys):
samples/samples/snippets_test.py:def test_query_with_struct(capsys):
samples/samples/snippets_test.py:def test_query_with_array_of_struct(capsys):
samples/samples/snippets_test.py:def test_query_struct_field(capsys):
samples/samples/snippets_test.py:def test_query_nested_struct_field(capsys):
samples/samples/snippets_test.py:def test_insert_data_with_dml(capsys):
samples/samples/snippets_test.py:def test_log_commit_stats(capsys):
samples/samples/snippets_test.py:def test_update_data_with_dml(capsys):
samples/samples/snippets_test.py:def test_delete_data_with_dml(capsys):
samples/samples/snippets_test.py:def test_update_data_with_dml_timestamp(capsys):
samples/samples/snippets_test.py:def test_dml_write_read_transaction(capsys):
samples/samples/snippets_test.py:def test_update_data_with_dml_struct(capsys):
samples/samples/snippets_test.py:def test_insert_with_dml(capsys):
samples/samples/snippets_test.py:def test_query_data_with_parameter(capsys):
samples/samples/snippets_test.py:def test_write_with_dml_transaction(capsys):
samples/samples/snippets_test.py:def test_create_table_with_datatypes(capsys):
samples/samples/snippets_test.py:def test_insert_datatypes_data(capsys):
samples/samples/snippets_test.py:def test_query_data_with_array(capsys):
samples/samples/snippets_test.py:def test_query_data_with_bool(capsys):
samples/samples/snippets_test.py:def test_query_data_with_bytes(capsys):
samples/samples/snippets_test.py:def test_query_data_with_date(capsys):
samples/samples/snippets_test.py:def test_query_data_with_float(capsys):
samples/samples/snippets_test.py:def test_query_data_with_int(capsys):
samples/samples/snippets_test.py:def test_query_data_with_string(capsys):
samples/samples/snippets_test.py:def test_add_numeric_column(capsys):
samples/samples/snippets_test.py:def test_update_data_with_numeric(capsys):
samples/samples/snippets_test.py:def test_query_data_with_numeric_parameter(capsys):
samples/samples/snippets_test.py:def test_query_data_with_timestamp_parameter(capsys):
samples/samples/snippets_test.py:def test_query_data_with_query_options(capsys):
samples/samples/snippets_test.py:def test_create_client_with_query_options(capsys):
```

Most of that is because one sample wants to show setup (e.g., creating the `Venues` table), and other samples depend on having that setup already done.  We could chose to use the [`pytest-dependency` plugin](https://pytest-dependency.readthedocs.io/en/stable/usage.html) to handle that case.

**Comment by tseaver** [comment]
@larkee I've opened #423 to sketch out how refactoring the samples test-drivers to use shared fixtures would look.

**Comment by tseaver** [comment]
Superseded by #423.

**Pull request closed without merging**
