### PR TITLE
feat: add progress field to UpdateDatabaseDdlMetadata

### PR DESCRIPTION
**Pull request by parthea**
This PR includes the latest generated client from [googleapis-gen](https://github.com/googleapis/googleapis-gen/tree/master/google/spanner). I also modified the `owlbot.py` script to properly copy multiple versions from googleapis-gen [here](https://github.com/googleapis/googleapis-gen/tree/master/google/spanner).

This PR also includes the following features and fixes:

feat: move import of CommitResponse
fix: add async client to %name_%version/init.py
chore: add autogenerated snippets
chore: remove auth, policy, and options from the reserved names list
feat: support self-signed JWT flow for service accounts
chore: enable GAPIC metadata generation
chore: sort subpackages in %namespace/%name/init.py

### CODE REVIEW

**Comment by parthea** [comment]
The build has the following error: `ImportError: cannot import name 'CommitResponse' ` . I'm looking into it.

**Comment by parthea** [comment]
There is an issue with the docs. I'm looking into it.
```
sphinx.errors.SphinxWarning: /usr/local/google/home/partheniou/git/python-spanner/google/cloud/spanner_v1/types/transaction.py:docstring of google.cloud.spanner_v1.types.transaction.TransactionOptions:4:Unexpected section title.
```

This [docstring](https://github.com/googleapis/python-spanner/pull/361/files#diff-da87f5702947744e8a5552a7f2678ecfdb8023cdf1995c296e802a272a28ac5eR30) has headings. I'm wondering if we should update the source proto to remove the headings based on [AIP-192](https://google.aip.dev/192#formatting).

**Comment by parthea** [comment]
Blocked by https://github.com/googleapis/synthtool/pull/1107

**Comment by parthea** [comment]
I'm going to switch this back to draft. It should be ready for review tomorrow.

**Review by larkee — APPROVED** [review]

**Pull request merged**
