### PR TITLE
feat(db_api): support JSON data type

### PR DESCRIPTION
**Pull request by IlyaFaer**

### CODE REVIEW

**Review by larkee — APPROVED** [review]

**Comment by larkee** [comment]
@IlyaFaer There are system test and sample failures relating to JSON comparisons because the assertions are expecting a JSON string but are getting a Python dict. This can be fixed by overriding the `__repr__` method on `JsonObject` to return `self.serialize()`.

**Comment by larkee** [comment]
@IlyaFaer There are lint errors and the sample assertions are still failing.

**Comment by IlyaFaer** [comment]
@larkee, oh, looks like some samples requires some work. Working on it...

**Comment by IlyaFaer** [comment]
@larkee, this one seems to be okay for merge.

**Pull request merged**
